# Generated by Django 3.1.2 on 2020-11-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_rate', models.FloatField()),
                ('articles', models.ManyToManyField(to='shop.Article')),
            ],
        ),
    ]
