# Generated by Django 3.1.2 on 2020-11-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_saleapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sale_price',
            field=models.FloatField(),
        ),
    ]
