# Generated by Django 3.1.2 on 2020-11-03 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20201103_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('sale_price', models.FloatField()),
                ('amount_avaliable', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='amount_avaliable',
        ),
        migrations.RemoveField(
            model_name='article',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='article',
            name='optional_properties',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='article',
            name='size',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Optional',
        ),
        migrations.AddField(
            model_name='item',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='rates',
            field=models.ManyToManyField(to='shop.Rate'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviews',
            field=models.ManyToManyField(to='shop.Review'),
        ),
    ]
