# Generated by Django 3.1.2 on 2020-11-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201103_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleapply',
            name='articles',
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleapply',
            name='items',
            field=models.ManyToManyField(to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rates',
            field=models.ManyToManyField(blank=True, to='shop.Rate'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='shop.Review'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.FloatField(blank=True),
        ),
    ]
