# Generated by Django 3.1.2 on 2020-11-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201104_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sale',
        ),
    ]
