# Generated by Django 3.1.2 on 2020-11-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_article_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='manual',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='shop.item')),
            ],
        ),
    ]
