# Generated by Django 3.1.2 on 2020-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201107_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rates',
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
