# Generated by Django 3.1.2 on 2020-11-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sale']},
        ),
    ]
