# Generated by Django 3.1.3 on 2020-11-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20201114_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['article']},
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
