# Generated by Django 3.1.3 on 2020-11-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20201122_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/articles/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'brand')},
        ),
    ]
