# Generated by Django 3.1.3 on 2020-12-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20201130_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='shop.item'),
        ),
        migrations.CreateModel(
            name='AccessionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_records', to='shop.item')),
            ],
        ),
    ]
