# Generated by Django 3.1.3 on 2020-12-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20201203_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_records', to='shop.item')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessionRecord',
        ),
    ]
